#!/usr/bin/env bash
trap 'rm -f ~/projects/Archipelago/output/apworlds/vex2.apworld; exit 0' TERM
python3.13 make_apworlds.py vex2 &>/dev/null
echo ~/projects/Archipelago/output/apworlds/vex2.apworld

while :; do
  sleep 1
done
