#!/usr/bin/env bash
trap 'rm -f ~/projects/Archipelago/output/apworlds/vex2.apworld; generate-global-tracker-data Vex2; exit 0' TERM
sed -i 's/"world_version": .*,/"world_version": "'"$VERSION"'.0.0",/' archipelago.json
python3.13 make_apworlds.py vex2 &>/dev/null
echo ~/projects/Archipelago/output/apworlds/vex2.apworld

while :; do
  sleep 1
done
