#!/usr/bin/env sh

if [ -z "$1" ]; then
  (../../.venv/bin/python3.13 ../../Generate.py && ../../.venv/bin/python3.13 ../../MultiServer.py "$(find ../../output/ -maxdepth 1 -name "AP_*.zip" -printf "%T@ %p\n" | sort -n | tail -n 1 | cut -d' ' -f2-)") 2>&1 | tee start.log | (gowoify || cat)
else
  (../../.venv/bin/python3.13 ../../MultiServer.py "$(find ../../output/ -maxdepth 1 -name "AP_$1.zip" -printf "%T@ %p\n" | sort -n | tail -n 1 | cut -d' ' -f2-)") 2>&1 | tee start.log | (gowoify || cat)
fi
